### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by haesleinhuepf** [HenriquesLab/napari-NanoPyx#1]
Hi all,

I just tried to install and use the plugin. I installed it like this:;
```
pip install napari-nanopyx
```

and then clicked this menu entry:

![image](https://github.com/HenriquesLab/napari-NanoPyx/assets/12660498/1a3fa9b7-4185-486a-9302-66f80476a8e7)

This error shows up:
```
File ~\mambaforge\envs\bio39\lib\site-packages\npe2\_command_registry.py:34, in CommandHandler.resolve(self=CommandHandler(id='napari-nanopyx.estimate_drift...anopyx.drift_alignment:estimate_drift_alignment'))
     32     self.function = utils.import_python_name(self.python_name)
     33 except Exception as e:
---> 34     raise RuntimeError(
        self.python_name = 'napari_nanopyx.drift_alignment:estimate_drift_alignment'
        self = CommandHandler(id='napari-nanopyx.estimate_drift_alignment', function=None, python_name='napari_nanopyx.drift_alignment:estimate_drift_alignment')
     35         f"Failed to import command at {self.python_name!r}: {e}"
     36     ) from e
     38 return self.function

RuntimeError: Failed to import command at 'napari_nanopyx.drift_alignment:estimate_drift_alignment': No module named 'nanopyx'
```

After installing nanopyx, it still does not work.

**Comment by brunomsaraiva** [comment]
Hi @haesleinhuepf, thanks for reporting the issue. NanoPyx was indeed missing from the requirements.
I've created a new release now properly listing the requirement, could you please give it a try and let us know whether the issue has now been fixed? (doing pip install napari-nanopyx should install napari-nanopyx 0.0.4 and nanopyx 0.1.2)
Thank you for your help.
