### ISSUE TITLE
User-documentation

### ISSUE THREAD

**Issue by haesleinhuepf** [HenriquesLab/napari-NanoPyx#3]
Hi all,

I'm just wondering if a new user wanted to learn how to use this napari plugin, where should one look for user-documentation?

Read more about user documentation: https://focalplane.biologists.com/2023/04/30/scientific-data-analysis-user-documentation-101/

Thanks!
Robert

**Comment by brunomsaraiva** [comment]
Hi,
We've created a wiki page that contains user focused documentation, although still an initial version it should now point the users in the right direction. We are planning on also releasing video tutorials that should be made available in the near future.

Thanks for the help,
Bruno

**Comment by haesleinhuepf** [comment]
Consider putting a link to the wiki in the readme. 😉

**Comment by brunomsaraiva** [comment]
There is one at the top labeled documentation, but I'll also add it as a text section :)
